import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Platform,
  ViewStyle,
  KeyboardAvoidingView,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../context/AuthContext';
import { getConsumptionHistory } from '../../Services/consumptionService';
import { getTenantPredictionAndTips, generateEnergyInsights } from '../../Services/aiService';

interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: Date;
}

export default function AIScreen() {
  const { user } = useAuth();
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [historyData, setHistoryData] = useState<any[]>([]);
  const scrollViewRef = useRef<ScrollView>(null);

  // System instructions para itakda ang eksaktong scope ng AI base sa documentation
  const SYSTEM_SCOPE_PROMPT = 
    "You are FairWatt AI, an expert Energy Analyst Chatbot. Your strict scope is to answer questions about electricity consumption, " +
    "provide actionable tips on how to save energy/money, calculate electricity estimates, and explain features of the FairWatt app. " +
    "Politely decline to answer questions completely unrelated to electricity, energy conservation, or the FairWatt app.";

  useEffect(() => {
    const unsubscribe = getConsumptionHistory((data) => {
      setHistoryData(data);
      setMessages([{
        id: 'welcome',
        text: "Hello! I am FairWatt AI. I've analyzed your consumption logs. How can I help you today? Ask me about your bill predictions or how you can save electricity!",
        sender: 'ai',
        timestamp: new Date(),
      }]);
    });
    return () => unsubscribe();
  }, [user]);

  useEffect(() => {
    setTimeout(() => scrollViewRef.current?.scrollToEnd({ animated: true }), 60);
  }, [messages]);

  const handleSendMessage = async () => {
    if (!inputText.trim()) return;
    const userMessageText = inputText.trim();
    setInputText('');
    setMessages((prev) => [...prev, {
      id: Date.now().toString(),
      text: userMessageText,
      sender: 'user',
      timestamp: new Date(),
    }]);

    setLoading(true);
    try {
      let aiResponse = '';
      if (userMessageText.toLowerCase().includes('predict') || userMessageText.toLowerCase().includes('bill')) {
        aiResponse = await getTenantPredictionAndTips(historyData);
      } else {
        // Ipinapasa ang system scope instruction kasama ang text ng user para manatili sa boundaries ang LLM
        aiResponse = await generateEnergyInsights(`${SYSTEM_SCOPE_PROMPT}\n\nUser Question: ${userMessageText}`);
      }
      setMessages((prev) => [...prev, {
        id: (Date.now() + 1).toString(),
        text: aiResponse,
        sender: 'ai',
        timestamp: new Date(),
      }]);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <SafeAreaView style={styles.mainWrapper} edges={['top', 'left', 'right']}>
      {/* 📌 PERMANENT STICKY TOP BAR: Labas sa ScrollView at KeyboardAvoidingView para hindi gagalaw o aalog */}
      <View style={styles.topBarContainer}>
        <Text style={styles.topBarTitle}>FairWatt AI</Text>
        <Text style={styles.topBarSubtitle}>Generated by AI • Energy Assistant</Text>
      </View>

      <KeyboardAvoidingView 
        behavior={Platform.OS === 'ios' ? 'padding' : undefined} 
        style={{ flex: 1 }}
      >
        {/* RESPONSIVE SCROLL VIEW: Ang usapan lamang ang gumagalaw kapag nag-scroll ang user */}
        <ScrollView 
          ref={scrollViewRef} 
          contentContainerStyle={styles.chatContainer}
          style={{ flex: 1 }}
          onContentSizeChange={() => scrollViewRef.current?.scrollToEnd({ animated: true })}
        >
          {messages.map((msg) => (
            <View
              key={msg.id}
              style={[
                styles.messageBubble,
                msg.sender === 'user' ? styles.userBubble : styles.aiBubble,
              ]}
            >
              <Text style={msg.sender === 'user' ? styles.userText : styles.aiText}>
                {msg.text}
              </Text>
            </View>
          ))}
          {loading && <ActivityIndicator style={{ margin: 10 }} color="#1A442E" />}
        </ScrollView>

        {/* INPUT LAYOUT */}
        <View style={styles.inputContainer}>
          <TextInput
            style={styles.input}
            placeholder="Ask anything about energy saving..."
            value={inputText}
            onChangeText={setInputText}
          />
          <TouchableOpacity style={styles.sendButton} onPress={handleSendMessage}>
            <Ionicons name="send" size={20} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  mainWrapper: { 
    flex: 1, 
    backgroundColor: '#F8FAFC' 
  },
  // Ginaya ang istilo ng top bar sa image_6dbf72.jpg: simple, malinis, at sentro ang text.
  topBarContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  topBarTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
    textAlign: 'center',
  },
  topBarSubtitle: {
    fontSize: 11,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 2,
  },
  chatContainer: { 
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    alignItems: 'center', // 🎯 NAKAGITNA: Awtomatikong pinapantay sa sentro ang mga mensahe
  },
  messageBubble: { 
    padding: 14, 
    borderRadius: 16, 
    marginBottom: 12, 
    width: '92%', // Tamang kalkulasyon ng lapad para maging maganda ang kapit sa gitna
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  userBubble: { 
    backgroundColor: '#1A442E', // Theme color ng FairWatt
  } as ViewStyle, 
  aiBubble: { 
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  } as ViewStyle,
  userText: { 
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 22
  },
  aiText: { 
    color: '#1E293B',
    fontSize: 15,
    lineHeight: 22
  },
  inputContainer: { 
    flexDirection: 'row', 
    paddingHorizontal: 16,
    paddingVertical: 12, 
    backgroundColor: '#FFFFFF', 
    borderTopWidth: 1, 
    borderColor: '#E2E8F0',
    alignItems: 'center'
  },
  input: { 
    flex: 1, 
    paddingHorizontal: 16,
    paddingVertical: 10, 
    backgroundColor: '#F1F5F9', 
    borderRadius: 24,
    fontSize: 15,
    color: '#1E293B'
  },
  sendButton: { 
    padding: 12, 
    backgroundColor: '#1A442E', 
    borderRadius: 24, 
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center'
  },
});