import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Platform,
  ViewStyle,
  KeyboardAvoidingView,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../context/AuthContext';
import { getConsumptionHistory } from '../../Services/consumptionService';
import { getTenantPredictionAndTips, generateEnergyInsights } from '../../Services/aiService';
import { Colors, Fonts, Radius } from '../../constants/theme';

interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: Date;
}

export default function AIScreen() {
  const { user, isDarkMode } = useAuth();
  const themeColors = isDarkMode ? Colors.dark : Colors.light;

  const [messages, setMessages] = useState<Message[]>([]);
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [historyData, setHistoryData] = useState<any[]>([]);
  const scrollViewRef = useRef<ScrollView>(null);

  // System instructions para itakda ang eksaktong scope ng AI base sa documentation
  const SYSTEM_SCOPE_PROMPT = 
    "You are FairWatt AI, an expert Energy Analyst Chatbot. Your strict scope is to answer questions about electricity consumption, " +
    "provide actionable tips on how to save energy/money, calculate electricity estimates, and explain features of the FairWatt app. " +
    "Politely decline to answer questions completely unrelated to electricity, energy conservation, or the FairWatt app.";

  useEffect(() => {
    const unsubscribe = getConsumptionHistory((data) => {
      setHistoryData(data);
      setMessages([{
        id: 'welcome',
        text: "Hello! I am FairWatt AI. I've analyzed your consumption logs. How can I help you today? Ask me about your bill predictions or how you can save electricity!",
        sender: 'ai',
        timestamp: new Date(),
      }]);
    });
    return () => unsubscribe();
  }, [user]);

  useEffect(() => {
    setTimeout(() => scrollViewRef.current?.scrollToEnd({ animated: true }), 60);
  }, [messages]);

  const handleSendMessage = async () => {
    if (!inputText.trim()) return;
    const userMessageText = inputText.trim();
    setInputText('');
    setMessages((prev) => [...prev, {
      id: Date.now().toString(),
      text: userMessageText,
      sender: 'user',
      timestamp: new Date(),
    }]);

    setLoading(true);
    try {
      let aiResponse = '';
      if (userMessageText.toLowerCase().includes('predict') || userMessageText.toLowerCase().includes('bill')) {
        aiResponse = await getTenantPredictionAndTips(historyData);
      } else {
        // Ipinapasa ang system scope instruction kasama ang text ng user para manatili sa boundaries ang LLM
        aiResponse = await generateEnergyInsights(`${SYSTEM_SCOPE_PROMPT}\n\nUser Question: ${userMessageText}`);
      }
      setMessages((prev) => [...prev, {
        id: (Date.now() + 1).toString(),
        text: aiResponse,
        sender: 'ai',
        timestamp: new Date(),
      }]);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <SafeAreaView style={[styles.mainWrapper, { backgroundColor: themeColors.background }]} edges={['top', 'left', 'right']}>
      {/* 📌 PERMANENT STICKY TOP BAR: Labas sa ScrollView at KeyboardAvoidingView para hindi gagalaw o aalog */}
      <View style={[styles.topBarContainer, { backgroundColor: themeColors.card, borderColor: themeColors.border }]}>
        <Text style={[styles.topBarTitle, { color: themeColors.primary }]}>FairWatt AI</Text>
        <Text style={[styles.topBarSubtitle, { color: themeColors.textSecondary }]}>Generated by AI • Energy Assistant</Text>
      </View>

      <KeyboardAvoidingView 
        behavior={Platform.OS === 'ios' ? 'padding' : undefined} 
        style={[styles.keyboardAvoidingView, { flex: 1 }]}
      >
        {/* RESPONSIVE SCROLL VIEW: Ang usapan lamang ang gumagalaw kapag nag-scroll ang user */}
        <ScrollView 
          ref={scrollViewRef} 
          contentContainerStyle={styles.chatContainer}
          style={{ flex: 1, width: '100%' }}
          showsVerticalScrollIndicator={false}
          onContentSizeChange={() => scrollViewRef.current?.scrollToEnd({ animated: true })}
        >
          {messages.map((msg) => (
            <View
              key={msg.id}
              style={[
                styles.messageBubble,
                msg.sender === 'user' ? [styles.userBubble, { backgroundColor: themeColors.primary }] : [styles.aiBubble, { backgroundColor: themeColors.card, borderColor: themeColors.border }],
              ]}
            >
              <Text 
                style={[
                  msg.sender === 'user' ? styles.userText : [styles.aiText, { color: themeColors.text }],
                  { fontFamily: 'Poppins_400Regular' }
                ]}
              >
                {msg.text}
              </Text>
            </View>
          ))}
          {loading && <ActivityIndicator style={{ margin: 10 }} color={themeColors.primary} />}
        </ScrollView>

        {/* INPUT LAYOUT */}
        <View style={[styles.inputContainer, { backgroundColor: themeColors.card, borderColor: themeColors.border }]}>
          <TextInput
            style={[styles.input, { backgroundColor: isDarkMode ? '#1E1E1E' : '#F1F5F9', color: themeColors.text }]}
            placeholder="Ask anything about energy saving..."
            placeholderTextColor={themeColors.textSecondary}
            value={inputText}
            onChangeText={setInputText}
          />
          <TouchableOpacity 
            style={[styles.sendButton, { backgroundColor: themeColors.primary }]} 
            onPress={handleSendMessage}
            activeOpacity={0.8}
          >
            <Ionicons name="send" size={18} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  mainWrapper: { 
    flex: 1, 
    alignItems: 'center',
    width: '100%',
  },
  topBarContainer: {
    width: '100%',
    maxWidth: 600,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1.5,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
  },
  topBarTitle: {
    ...Fonts.h3,
    fontWeight: '700',
    textAlign: 'center',
  },
  topBarSubtitle: {
    ...Fonts.caption,
    textAlign: 'center',
    marginTop: 2,
  },
  keyboardAvoidingView: {
    width: '100%',
    maxWidth: 600,
    flex: 1,
  },
  chatContainer: { 
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    alignItems: 'center',
    width: '100%',
  },
  messageBubble: { 
    padding: 14, 
    borderRadius: Radius.card - 6, 
    marginBottom: 12, 
    width: '94%',
    alignSelf: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
  },
  userBubble: { 
    alignSelf: 'flex-end',
  } as ViewStyle, 
  aiBubble: { 
    alignSelf: 'flex-start',
    borderWidth: 1.5,
  } as ViewStyle,
  userText: { 
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 22,
  },
  aiText: { 
    fontSize: 14,
    lineHeight: 22,
  },
  inputContainer: { 
    flexDirection: 'row', 
    paddingHorizontal: 16,
    paddingVertical: 12, 
    borderTopWidth: 1.5, 
    alignItems: 'center',
    width: '100%',
  },
  input: { 
    flex: 1, 
    paddingHorizontal: 16,
    height: 48,
    borderRadius: Radius.button + 12,
    fontSize: 14,
    fontFamily: 'Poppins_400Regular',
  },
  sendButton: { 
    width: 44,
    height: 44,
    borderRadius: 22, 
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
});